### ISSUE TITLE
Redelegate DNS

### ISSUE THREAD

**Issue by AshleyRoll** [barcvk4ba/barcvk4ba.github.io#9]
* [x] Redelegate DNS to new name servers
* [x] Create A record for apex domain (@) to:
  * 185.199.108.153
  * 185.199.109.153
  * 185.199.110.153
  * 185.199.111.153
* [x] Create a CNAME record to point `www` to `barcvk4ba.github.io`
* [x] Add CNAME file to repo for Gitub Pages Support for domain name. single line `barcvk4ba.com.au`

**Comment by AshleyRoll** [comment]
Had to remove CNAME as it was causing GitHub to redirect, but we don't have the DNS delegations in place yet.

**Comment by bahima25** [comment]
Hey Ash,
All delegated and done. Looks good!

**Comment by bahima25** [comment]
- [ ] Enable HTTPS when cert is generated.

**Comment by AshleyRoll** [comment]
I enabled HTTPS.
